version: '3.4'
services:
  all-in-one-modelo-share:
    image: alfresco-share-all-in-one-modelo:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../all-in-one-modelo-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: all-in-one-modelo-acs
      REPO_PORT: 8080
    ports:
      - "8180:8080"
      - "9898:8888"
  all-in-one-modelo-acs:
    image: alfresco-content-services-all-in-one-modelo:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../all-in-one-modelo-platform-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "-Dencryption.keystore.type=JCEKS
			-Dencryption.cipherAlgorithm=AES/CBC/PKCS5Padding
			-Dencryption.keyAlgorithm=AES
			-Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
			-Dmetadata-keystore.password=mp6yc0UD9e
			-Dmetadata-keystore.aliases=metadata
			-Dmetadata-keystore.metadata.password=oKIWzVdEdA
			-Dmetadata-keystore.metadata.algorithm=AES"
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - all-in-one-modelo-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - all-in-one-modelo-postgres
  all-in-one-modelo-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5555:5432"
    volumes:
      - all-in-one-modelo-db-volume:/var/lib/postgresql/data
  all-in-one-modelo-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: all-in-one-modelo-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: all-in-one-modelo-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - all-in-one-modelo-ass-volume:/opt/alfresco-search-services/contentstore
      - all-in-one-modelo-ass-volume:/opt/alfresco-search-services/data
volumes:
  all-in-one-modelo-acs-volume:
    external: true
  all-in-one-modelo-db-volume:
    external: true
  all-in-one-modelo-ass-volume:
    external: true
